name = "buat"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "2dd86067-7257-4314-a8e8-3ebf9e7e77af"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
